import { StyleSheet } from 'react-native';
import { colors } from '../../theme/colors';

export const WIZARD_ACCENT = '#70088c';

export const wizardStyles = StyleSheet.create({
  root: { flex: 1, backgroundColor: '#f8fafc' },
  flex: { flex: 1 },
  header: {
    backgroundColor: WIZARD_ACCENT,
    paddingBottom: 10,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingTop: 4,
    minHeight: 48,
  },
  backBtn: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  backText: {
    color: '#fff',
    fontSize: 32,
    lineHeight: 34,
    fontWeight: '300',
    marginTop: -2,
  },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
    color: '#fff',
    fontSize: 17,
    fontWeight: '700',
  },
  headerSpacer: { width: 40 },
  progressTrack: {
    height: 3,
    backgroundColor: 'rgba(255,255,255,0.25)',
    marginHorizontal: 16,
    borderRadius: 2,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    backgroundColor: '#fff',
  },
  content: {
    paddingHorizontal: 20,
    paddingTop: 18,
    paddingBottom: 24,
  },
  stepCount: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    color: WIZARD_ACCENT,
    marginBottom: 6,
  },
  title: {
    fontSize: 24,
    fontWeight: '800',
    color: colors.navy900,
    marginBottom: 6,
  },
  subtitle: {
    fontSize: 14,
    lineHeight: 20,
    color: colors.muted,
    marginBottom: 18,
  },
  fieldLabel: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    color: colors.navy800,
    marginBottom: 6,
  },
  fieldSpaced: { marginTop: 12 },
  input: {
    height: 50,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    paddingHorizontal: 14,
    fontSize: 16,
    color: colors.heading,
    backgroundColor: '#fff',
  },
  hint: {
    marginTop: 10,
    fontSize: 12,
    lineHeight: 17,
    color: colors.muted,
  },
  error: {
    marginTop: 12,
    color: colors.error,
    fontSize: 13,
    lineHeight: 18,
  },
  footerSafe: {
    backgroundColor: '#fff',
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.border,
  },
  primaryBtn: {
    marginHorizontal: 16,
    marginVertical: 10,
    height: 50,
    borderRadius: 12,
    backgroundColor: WIZARD_ACCENT,
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryBtnDisabled: { opacity: 0.75 },
  primaryBtnText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '800',
    letterSpacing: 0.3,
  },
  optionCard: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: colors.border,
    borderRadius: 14,
    padding: 14,
    backgroundColor: '#fff',
    marginBottom: 10,
  },
  optionCardSelected: {
    borderColor: WIZARD_ACCENT,
    backgroundColor: '#faf5ff',
  },
  optionCardPressed: {
    opacity: 0.92,
  },
  optionBody: {
    flex: 1,
    minWidth: 0,
    paddingRight: 6,
  },
  optionTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.navy900,
  },
  optionMeta: {
    marginTop: 4,
    fontSize: 12,
    lineHeight: 16,
    color: colors.muted,
  },
  optionChevron: {
    fontSize: 26,
    lineHeight: 28,
    fontWeight: '300',
    color: WIZARD_ACCENT,
    marginLeft: 4,
  },
  phoneChip: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 14,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: '#f3e8ff',
    borderWidth: 1,
    borderColor: '#e9d5ff',
  },
  phoneChipLabel: {
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    color: WIZARD_ACCENT,
  },
  phoneChipValue: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.navy900,
  },
});
